version: '3'

services:
  backend:
    image: gcr.io/opa-268409/opa-backend:latest
    ports:
      - "9000"
  proxy:
    image: caddy/caddy
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from api.opa.social/v1 --to backend:9000