version: '3'

services:
  backend:
    image: gcr.io/opa-268409/opa-backend:latest
    ports:
      - "9000"
    environment:
      FIREBASE_CONFIG: /config/firebase-config.json
    volumes:
      - ${FIREBASE_CONFIG}:/config/firebase-config.json:ro
  proxy:
    image: caddy/caddy
    ports:
      - "80:80"
      - "443:443"
    command: reverse-proxy --from api.opa.social/v1 --to backend:9000